services:
  db:
    image: mysql:8.0-debian
    container_name: gr6_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: usuario
      MYSQL_DATABASE: gr6_db
      MYSQL_USER: user_gr6
      MYSQL_PASSWORD: usuario
    ports:
      - "33070:33060"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./app/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql

  flask-app:
    build: .
    container_name: flask_lockers
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=10.3.29.20
      - DB_PORT=33060
      - DB_USER=user_gr6
      - DB_PASSWORD=usuario
      - DB_NAME=gr6_db
    env_file:
      - taquillas-env

volumes:
  mysql_data: